export enum textTypes {
  TITLE_REGULAR, //26PX
  TITLE_LIGHT,
  TITLE_BOLD,
  SUBTITLE_REGULAR, //24PX
  SUBTITLE_LIGHT,
  SUBTITLE_BOLD,
  BUTTON_REGULAR, //20PX
  BUTTON_LIGHT,
  BUTTON_BOLD,
  PARAGRAPH_REGULAR, //16PX
  PARAGRAPH_LIGHT,
  PARAGRAPH_BOLD,
  PARAGRAPH_SMALL_REGULAR, //14PX
  PARAGRAPH_SMALL_LIGHT,
  PARAGRAPH_SMALL_BOLD,
}
